languageCode = "en-us"
title = "Sting's Note"
baseURL = "https://stingh711.github.io/"

publishDir = "../output"

theme="hyde"

googleAnalytics = "UA-10412053-2"

[params]
    disqusShortname = "stingh711"
